#----------------------------------------------------------
# The file use for deployment of file-svc into k8s
# Thou notice that 4 sections:
# 1- Namespace
# 2- Deploy app with name of xdoc-web run in container
# 3- Create service point to xdoc-web app with name xdoc-web-service
# 4- Expose xdoc-web-service via ingress
#----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: facebook-duckling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-duckling
  namespace: facebook-duckling
spec:
  selector:
    matchLabels:
      app: facebook-duckling
  replicas: 1
  template:
    metadata:
      labels:
        app: facebook-duckling
    spec:
      containers:
        - image: rasa/duckling:latest
          name: facebook-duckling
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
 name: facebook-duckling
 namespace: facebook-duckling
 labels:
   app: facebook-duckling
spec:
 type: NodePort
 selector:
   app: facebook-duckling
 ports:
 - port: 8082
   targetPort: 8000
   protocol: TCP
   nodePort: 31009

