#----------------------------------------------------------
# The file use for deployment of file-svc into k8s
# Thou notice that 4 sections:
# 1- Namespace
# 2- Deploy app with name of xdoc-web run in container
# 3- Create service point to xdoc-web app with name xdoc-web-service
# 4- Expose xdoc-web-service via ingress
#----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: lv-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabitmq
  namespace: lv-broker
spec:
  selector:
    matchLabels:
      app: rabitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabitmq
    spec:
      containers:
        #docker run -d --hostname my-rabbit --name some-rabbit-1 rabbitmq:3 -p 5672:5672 -p 15672:15672
        - image: rabbitmq:3
          name: rabitmq
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"


---
apiVersion: v1
kind: Service
metadata:
  name: rabitmq-service
  namespace: lv-broker
  labels:
    app: rabitmq
spec:
  type: NodePort
  selector:
    app: rabitmq
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    nodePort: 31672
---
---
apiVersion: v1
kind: Service
metadata:
  name: rabitmq-ui
  namespace: lv-broker
  labels:
    app: rabitmq
spec:
  type: NodePort
  selector:
    app: rabitmq
  ports:
    - name: "15672"
      port: 15672
      targetPort: 15672
      nodePort: 31673

