{{ $configName := $.Values.config.configName -}}
{{ $storageConfigType := $.Values.storageConfig.type -}}
{{ $configuration := $.Values.config -}}

{{ $storageConfig := get $.Values.storageConfig $storageConfigType -}}
{{ $configs := get $configuration $configName -}}
{{ $jsonConfig := toPrettyJson  $configs -}}
{{ $jsonStorageConfig := toPrettyJson  $storageConfig -}}

  {{ $webConfig := $.Values.webConfig}}
  {{ $webDeployType := $webConfig.type}}
  {{ $web := get  $webConfig $webConfig.type}}
{{ $webDeployment :=  $webConfig.isAllowDeploy}}

#{{ print "Thou is deploying with config :" }}
#{{ print "All information is bellow :" }}

#{{- range $key, $value := $configs}}
#  {{print $key}} : {{print $value}}
# {{end}}
#{{- range $key, $value := $storageConfig}}
#  {{print $key}} : {{print $value}}
# {{end}}
---
# Web deployment
---
{{if eq $webDeployment true}}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{$.Values.namespace}}
  labels:
    name: {{$.Values.namespace}}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$.Values.storageConfig.name}}
  namespace: {{$.Values.namespace}}
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: {{$.Values.storageConfig.className}}
  resources:
    requests:
      storage: {{$.Values.storageConfig.size}}
---
{{end}}
---
{{if ne $.Values.existConfigMap true}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xdoc-job-config
  namespace: {{$.Values.namespace}}
data:
  admin_db_name: {{ $configs.db.admin_db_name }}
  db.authSource: '{{ $configs.db.authSource }}'
  db.host: '{{ $configs.db.host }}'
  db.password: '{{ $configs.db.password }}'
  db.port: '{{ $configs.db.port }}'
  db.username: '{{ $configs.db.username }}'
  elastic_search.prefix_index: lv-codx
  elastic_search.server: '{{ $configs.elastic_search.server }}'
  rabbitmq.port: '{{ $configs.rabbitmq.port }}'
  rabbitmq.server: '{{ $configs.rabbitmq.server }}'
  temp_directory: './brokers/tmp'
---
{{end}}
---
{{- range $key, $value := .Values.deployments }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$value.name}}
  namespace: {{$.Values.namespace}}
  annotations:
    description: "{{$value.description | default $.Values.defaults.description }}"
spec:
  selector:
    matchLabels:
      app: files-{{$value.name}}
  replicas: {{$value.replicas | default $.Values.defaults.replicas}}
  template:
    metadata:
      labels:
        app: files-{{$value.name}}
    spec:


      volumes:
        - name: {{$storageConfig.name}}
        {{if hasKey  $storageConfig "className"}}
          persistentVolumeClaim:
            claimName: {{$storageConfig.name}}
        {{else}}
          nfs:
            server: {{$storageConfig.server}}
            path: {{$storageConfig.directory}}
        {{end}}

      containers:
        - args:
            - python3
            - /app/cy_consumers/files_upload.py
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)
            - admin_db_name= $(admin_db_name)
            - db.username=$(db.username)
            - db.password=$(db.password)
            - db.authSource=$(db.authSource)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
          image: {{ $.Values.image.repository  }}:{{$.Values.image.tag}}

          envFrom:
            - configMapRef:
                name: xdoc-job-config

          name: files-{{$value.name}}
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - mountPath: /app/share-storage
              name:  {{$storageConfig.name}}

---
{{- end }}
---
{{- range $key, $value := .Values.jobs}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$value.name}}
  namespace: {{$.Values.namespace}}
  annotations:
    description: "{{$value.description | default $.Values.defaults.description }}"
spec:
  template:
    spec:
      volumes:
        - name: {{$storageConfig.name}}
          {{if hasKey  $storageConfig "className"}}
          persistentVolumeClaim:
            claimName: {{$storageConfig.name}}
          {{else}}
          nfs:
            server: {{$storageConfig.server}}
            path: {{$storageConfig.directory}}
          {{end}}
      containers:
      - image: {{ $value.image  }}
        name: {{$value.name}}
        imagePullPolicy: IfNotPresent

        volumeMounts:
          - mountPath: /app/share-storage
            name:  {{$storageConfig.name}}
      restartPolicy: Never
  backoffLimit: 4
---
{{- end }}

# if really web need deployment
{{if eq  $.Values.storageConfig.isUse true}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{$web.name}}
---
metadata:
  name: {{$web.name}}-config
  namespace: {{$web.namespace}}
data:
  admin_db_name: {{ $configs.db.admin_db_name }}
  db.authSource: '{{ $configs.db.authSource }}'
  db.host: '{{ $configs.db.host }}'
  db.password: '{{ $configs.db.password }}'
  db.port: '{{ $configs.db.port }}'
  db.username: '{{ $configs.db.username }}'
  elastic_search.prefix_index: lv-codx
  elastic_search.server: '{{ $configs.elastic_search.server }}'
  rabbitmq.port: '{{ $configs.rabbitmq.port }}'
  rabbitmq.server: '{{ $configs.rabbitmq.server }}'
  temp_directory: './brokers/tmp'
---
# The first we need deploy an application where Pod of web will run inside
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$web.name}}
  namespace: {{$web.namespace}}
spec:
  selector:
    matchLabels:
      app: {{$web.name}}
  replicas: {{$.Values.defaults.replicas}}
  template:
    metadata:
      labels:
        app: xdoc-web
    spec:
      volumes:
        - name: {{$storageConfig.name}}
          {{if hasKey  $storageConfig "className"}}
          persistentVolumeClaim:
            claimName: {{$storageConfig.name}}
          {{else}}
          nfs:
            server: {{$storageConfig.server}}
            path: {{$storageConfig.directory}}
          {{end}}
      containers:
        - args:
            - python3
            - /app/cy_xdoc/server.py
            - bind=0.0.0.0:80
            - content_segment_len=9
            - host_url='{{$web.hostUrl}}'
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)

            - admin_db_name= $(admin_db_name)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
          image: {{ $.Values.image.repository  }}:{{$.Values.image.tag}}
          envFrom:
            - configMapRef:
                name: xdoc-web-config
          name: xdoc-web
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/share-storage
              name: {{$storageConfig.name}}
          ports:
            - containerPort: 80
---
# The second we need deploy a Service where application could be accessed by another
apiVersion: v1
kind: Service
metadata:
 name: {{$web.name}}
 namespace: {{$web.namespace}}
 labels:
   app: {{$web.name}}
spec:
#  type: NodePort
 selector:
   app: {{$web.name}}
 ports:
 - port: 8082
   targetPort: 80
   protocol: TCP
---
{{end}}