kind: Namespace
apiVersion: v1
metadata:
  name: {{$.Values.namespace}}
  labels:
    name: {{$.Values.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: xdoc-job-config
  namespace: {{$.Values.namespace}}
data:
  admin_db_name: lv-docs
  db.authSource: hps-file-test
  db.host: 192.168.18.36
  db.password: ''
  db.port: '27018'
  db.username: ''
  elastic_search.prefix_index: lv-codx
  elastic_search.server: http://192.168.18.36:9200
  rabbitmq.port: '5672'
  rabbitmq.server: rabbitmq.rabbitmq-dev
  temp_directory: ./brokers/tmp
---
{{- range $key, $value := .Values.deployments }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$value.name}}
  namespace: {{$.Values.namespace}}
  annotations:
    description: "{{$value.description | default $.Values.defaults.description }}"
spec:
  selector:
    matchLabels:
      app: files-{{$value.name}}
  replicas: {{$value.replicas | default $.Values.defaults.replicas}}
  template:
    metadata:
      labels:
        app: files-{{$value.name}}
    spec:
      volumes:
        - name: xdoc-storage
          nfs:
            server: {{$.Values.nfs.server}}
            path: {{$.Values.nfs.directory}}


      containers:
        - args:
            - python3
            - /app/cy_consumers/{{$value.endpoint}}
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)
            - admin_db_name=$(admin_db_name)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
          image: {{ $.Values.image.repository  }}:{{$.Values.image.tag}}

          envFrom:
            - configMapRef:
                name: xdoc-job-config

          name: files-{{$value.name}}
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - mountPath: /app/share-storage
              name: xdoc-storage

---
{{- end }}
---
{{- range $key, $value := .Values.jobs}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$value.name}}
  namespace: {{$.Values.namespace}}
  annotations:
    description: "{{$value.description | default $.Values.defaults.description }}"
spec:
  template:
    spec:
      volumes:
        - name: xdoc-storage
          nfs:
            server: {{$.Values.nfs.server}}
            path: {{$.Values.nfs.directory}}
      containers:
      - image: {{ $value.image  }}
        name: {{$value.name}}
        imagePullPolicy: IfNotPresent

        volumeMounts:
          - mountPath: /app/share-storage
            name: xdoc-storage
      restartPolicy: Never
  backoffLimit: 4
---
{{- end }}
#helm uninstall xdoc-job-v15
#helm install xdoc-job-v15 xdoc-job-18
#scp -r root@172.16.13.72:/home/vmadmin/python/v6/file-service-02/docker-build/helm/xdoc-job /nttlong/helm/xdoc-job