kind: Namespace
apiVersion: v1
metadata:
  name: {{$.Values.namespace}}
  labels:
    name: {{$.Values.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: xdoc-job-config
  namespace: {{$.Values.namespace}}
data:
  admin_db_name: lv-docs
  db.authSource: hps-file-test
  db.host: 192.168.18.36
  db.password: ''
  db.port: '27018'
  db.username: ''
  elastic_search.prefix_index: lv-codx
  elastic_search.server: http://192.168.18.36:9200
  rabbitmq.port: '5672'
  rabbitmq.server: rabbitmq.rabbitmq-dev
  temp_directory: ./brokers/tmp
---
{{- range $key, $value := .Values.deployments }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$value.name}}
  namespace: {{$.Values.namespace}}
  annotations:
    description: "{{$value.description | default $.Values.defaults.description }}"
spec:
  selector:
    matchLabels:
      app: files-{{$value.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: files-{{$value.name}}
    spec:
      volumes:
        - name: xdoc-temp-storage
          nfs:
            server: {{$.Values.nfs.server}}
            path: {{$.Values.nfs.directory}}/xdoc-web
        - name: xdoc-dataset
          nfs:
            server: {{$.Values.nfs.server}}
            path: {{$.Values.nfs.directory}}/dataset

      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [
            "sh",
            "-c",
            "mkdir -p /app/brokers",
            "chmod -R 777 /app/brokers",
            "chown -R nfsnobody:nfsnobody /app/brokers",
            "mkdir -p /app/dataset",
            "chmod -R 777 /app/dataset",
            "chown -R nfsnobody:nfsnobody /app/dataset",

          ]
          volumeMounts:
            - mountPath: /app/brokers
              name: xdoc-temp-storage
            - mountPath: /app/dataset
              name: xdoc-dataset
      containers:
        - args:
            - python3
            - /app/cy_consumers/{{$value.endpoint}}
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)
            - admin_db_name=$(admin_db_name)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)

          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          envFrom:
            - configMapRef:
                name: xdoc-job-config

          name: files-{{$value.name}}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/brokers
              name: xdoc-temp-storage
            - mountPath: /app/dataset
              name: xdoc-dataset
---
{{- end }}
#scp -r root@172.16.13.72:/home/vmadmin/python/v6/file-service-02/docker-build/helm/xdoc-job /nttlong/helm/xdoc-job