#----------------------------------------------------------
# The file use for deployment of file-svc into k8s
# Thou notice that 4 sections:
# 1- Namespace
# 2- Deploy app with name of xdoc-web run in container
# 3- Create service point to xdoc-web app with name xdoc-web-service
# 4- Expose xdoc-web-service via ingress
#----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: xdoc-dev-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xdoc-web-config-dev-test
  namespace: xdoc-dev-test
data:
  elastic_search.server: "http://lv-es.es-sn:9092" #http://172.16.0.83:9200/
  rabbitmq.server: "rabitmq-service.lv-broker" #	rabbitmq.rabbitmq-dev.svc.cluster.local5672


  elastic_search.prefix_index: "lv-codx"
  rabbitmq.port: "5672"
  host_url: "http://172.16.7.91/lvfile" #http://172.16.0.240/lvfile
  db.host: "192.168.18.36" #172.16.0.83
  db.port: "27018" #27017

  temp_directory: "./brokers/tmp"



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdoc-web
  namespace: xdoc-dev-test
spec:
  selector:
    matchLabels:
      app: xdoc-web
  replicas: 1
  template:
    metadata:
      labels:
        app: xdoc-web
    spec:
      volumes:
        - name: xdoc-temp-storage
          nfs:
            server: 172.16.7.91 #172.16.0.83
            path: /var/nfs_share_dir_for_k8s/xdoc-web #/data/share/xdoc-web
        - name: xdoc-web-cache
          nfs:
            server: 172.16.7.91
            path: /var/nfs_share_dir_for_k8s/xdoc-web-cache #/data/share/xdoc-web-cache
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [
            "sh", "-c",
            "chmod -R 777 /app/brokers", "chown -R nfsnobody:nfsnobody /app/brokers",
            "chmod -R 777 /app/cy_xdoc/cache","chown -R nfsnobody:nfsnobody /app/cy_xdoc/cache"
          ]
          volumeMounts:
            - mountPath: /app/brokers
              name: xdoc-temp-storage
            - mountPath: app/cy_xdoc/cache
              name: xdoc-web-cache

      containers:
        - args:
            - python3
            - /app/cy_xdoc/server.py
            - bind=0.0.0.0:80
            - content_segment_len=9
            - host_url=$(host_url)
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)
            - db.username=$(db.username)
            - db.password=$(db.password)
            - db.authSource=$(db.authSource)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
          image: nttlong/lv-file:rc.1.0.3 #nttlong/lv-file:rc.1.0.3
          envFrom:
            - configMapRef:
                name: xdoc-web-config-dev-test
          name: xdoc-web
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/brokers
              name: xdoc-temp-storage
            - mountPath: /app/cy_xdoc/cache
              name: xdoc-web-cache
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: xdoc-web-service
  namespace: xdoc-dev-test
  labels:
    app: xdoc-web
spec:
  type: NodePort
  selector:
    app: xdoc-web
  ports:
  - port: 8082
    targetPort: 80
    protocol: TCP
    nodePort: 31000


