apiVersion: v1
kind: Namespace
metadata:
  name: kafka-sn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka-sn
spec:
  clusterIP: None
#  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
#      nodePort: 30181
#      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka-sn
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      #/opt/kafka is a map dir
      hostname: kafka-broker
      containers:
      - env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
                #HOSTNAME_COMMAND: curl http://169.254.169.254/latest/meta-data/public-hostname
              #KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
              #KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
              #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
              #KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

        #listeners=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
          #listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
          #advertised.listeners=INTERNAL://localhost:9093,EXTERNAL://10.0.2.2:9092
          #inter.broker.listener.name=INTERNAL
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: $(MY_POD_IP)
        - name: MESSAGE_MAX_BYTES
          value: "2000000"
#        - name: KAFKA_LISTENERS
#          value: INTERNAL://0.0.0.0:9093,EXTERNAL://$(MY_POD_IP):9092
#        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT


        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(MY_POD_IP):9092 # INTERNAL://localhost:9093,EXTERNAL://broker-service.kafka-sn:30992
#        - name: KAFKA_INTER_BROKER_LISTENER_NAME
#          value: INTERNAL
        - name:  KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service.kafka-sn:2181


        image: confluentinc/cp-kafka

#        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-service
  name: broker-service
  namespace: kafka-sn
spec:
  externalTrafficPolicy: Local
#  type: LoadBalancer
  type: NodePort
  ports:
    - name: broker-port
      port: 9092
      nodePort: 30992
      targetPort: 9092
      protocol: "TCP"
  selector:
    app: kafka-broker