dataForm : 'dev'
image:
  repository: nttlong/files-service-final
  pullPolicy: IfNotPresent
  tag: "rc.0.5.3.0"
    #The tag name is describe how many stage in image:
  # rc: release candidate
  # 1 - The first number is embodied of the generation of image, it is also a first stage of image
  # where all necessary components at OS level support for all PODs run  (till now is the first generation)
  # 2 - The second number is embodied of the Open-Core-Stage where Open-Core-Stage were installed.
  # Those libraries did not write at Lac Viet. Such as MongoDb driver, pytorch,...
  # 3 - The third number is embodied of the Core-Stage . All core-library were write and compile at Lac Viet.
  # 4 - The final number is embodied of End-Point Pod start . All End-Point Pod were write and compile at Lac Viet.
defaults:
  replicas: 2
# if thou are deploying all Pods in K8S with 3 Worker-Nodes
# Thou could set this value is 3
# Expalination:
# The number of Pods in all deployments by default will be set by this value.
  description: "Uprate version"
  executor: "python3"
# The most Pods in all Deployment are using python3
  restartPolicy: Always
  kind: Deployment # do not care about that
  apiVersion: apps/v1 # do not care about that