#----------------------------------------------------------
# The file use for deployment of simple Kylin for POC not for production into k8s
# Thou notice that 4 sections:
# 1- Namespace
# 2- Deploy app with name of xdoc-web run in container
# 3- Create service point to xdoc-web app with name xdoc-web-service
# 4- Expose xdoc-web-service via ingress
#----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: kylin
---
#docker run -d -m 8G -p 7070:7070 -p 8088:8088 -p 50070:50070 -p 8032:8032 -p 8042:8042 -p 2181:2181 apachekylin/apache-kylin-standalone:5.0.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kylin-app
  namespace: kylin
spec:
  selector:
    matchLabels:
      app: kylin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kylin-app
    spec:
      containers:
        - args:
            - /home/admin/entrypoint.sh
          image: apachekylin/apache-kylin-standalone:kylin-4.0.1-mondrian
          name: apache-kylin-standalone
          imagePullPolicy: IfNotPresent
          ports:
            #-p 7070:7070 \
            #-p 7080:7080 \
            #-p 8088:8088 \
            #-p 50070:50070 \
            #-p 8032:8032 \
            #-p 8042:8042 \
            #-p 2181:2181 \
            - containerPort: 7070
            - containerPort: 7080
            - containerPort: 8088
            - containerPort: 50070
            - containerPort: 8042
            - containerPort: 2181

          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  name: kylin-ui
  namespace: kylin
  labels:
    app: kylin-app
spec:
  type: NodePort
  selector:
    app: kylin-app
  ports:
  - port: 7070
    targetPort: 7070
    protocol: TCP
    nodePort: 30770
---
apiVersion: v1
kind: Service
metadata:
  name: kylin-ui-mdx
  namespace: kylin
  labels:
    app: kylin-app
spec:
  type: NodePort
  selector:
    app: kylin-app
  ports:
  - port: 7080
    targetPort: 7080
    protocol: TCP
    nodePort: 30780
---
apiVersion: v1
kind: Service
metadata:
  name: kylin-ui-hdfs
  namespace: kylin
  labels:
    app: kylin-app
spec:
  type: NodePort
  selector:
    app: kylin-app
  ports:
  - port: 50070
    targetPort: 50070
    protocol: TCP
    nodePort: 30570
---
apiVersion: v1
kind: Service
metadata:
  name: kylin-ui-yarn-resource
  namespace: kylin
  labels:
    app: kylin-app
spec:
  type: NodePort
  selector:
    app: kylin-app
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    nodePort: 30888
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: xdoc-web-ingress
#  namespace: xdoc
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
##    nginx.ingress.kubernetes.io/use-regex: "true"
##    nginx.ingress.kubernetes.io/rewrite-target: /$1
#
#spec:
#  ingressClassName: nginx #nginx or lv-file-ingress
#  rules:
##    - host: myservicea.foo.org
#     - http:
#        paths:
#          - pathType: Prefix
#            path: /lvfile
#            backend:
#              service:
#                name: xdoc-web-service
#                port:
#                  number: 8082
##  rules:
##    - http:
##        paths:
##          - pathType: Prefix
##            path: "/(.+)"
##            backend:
##              service:
##                name: xdoc-web-service
##                port:
##                  number: 8017
#
