    {{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") }}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
    {{- $dataJson := toPrettyJson $data }}
#------------------------------------------------------
# just for debug. no more ...
#------------------------------------------------------
