---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}

    {{ $data := .Files.Get $dataFile | fromYaml -}}
  {{ $jobsData := .Files.Get "data/jobs.apps.yml" | fromYaml -}}
  {{ $jobs := $jobsData.data -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $jobs -}}
  {{if $fileJob}}
---
{{if $jobsData.data}}
---
{{- range $key, $value := $jobs }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$value.name}}
  namespace: {{$fileJob.namespace}}
  annotations:
    description: {{$value.description | default "..." }}
spec:
  selector:
    matchLabels:
      app: files-{{$value.name}}
  replicas: {{$value.replicas | default $fileJob.replicas}}
  template:
    metadata:
      labels:
        app: files-{{$value.name}}
    spec:


      volumes:
        - name: {{$storage.name}}
        {{if hasKey  $storage "className"}}
          persistentVolumeClaim:
            claimName: {{$storage.name}}
        {{else}}
          nfs:
            server: {{$storage.server}}
            path: {{$storage.directory}}
        {{end}}

      containers:
        - args:
            - python3
            - /app/cy_consumers/{{$value.endpoint}}
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db.host=$(db.host)
            - db.port=$(db.port)
            - admin_db_name= $(admin_db_name)
            - db.username=$(db.username)
            - db.password=$(db.password)
            - db.authSource=$(db.authSource)
            - temp_directory=$(temp_directory)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
          image: {{ $fileJob.repository  }}:{{$fileJob.tag}}

          envFrom:
            - configMapRef:
                name: {{$storage.name}}

          name: files-{{$value.name}}
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - mountPath: {{$fileJob.mountPath}}
              name:  {{$storage.name}}

---
{{- end }}
---
{{end}}
  {{end}}