---
    {{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
    {{ $dataJson := toPrettyJson $api -}}


---
{{ if $api }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$api.configMapName}}
  namespace: {{$api.namespace}}
data:
  admin_db_name: {{ $db.admin_db_name }}
  db.authSource: '{{ $db.authSource }}'
  db.host: '{{ $db.host }}'
  db.password: '{{ $db.password }}'
  db.port: '{{ $db.port }}'
  db.username: '{{ $db.username }}'
  elastic_search.prefix_index: '{{$es.prefix_index}}'
  elastic_search.server: '{{ $es.server }}'
  rabbitmq.port: '{{ $rb.port }}'
  rabbitmq.server: '{{ $rb.server }}'
  temp_directory: './brokers/tmp'
---
{{end}}