apiVersion: v1
kind: Namespace
metadata:
  name: db-gate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbgate
  name: dbgate-service
  namespace: db-gate
spec:
#  clusterIP: None
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31333
      targetPort: 3000
  selector:
    app: dbgate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbgate
  namespace: db-gate
spec:
  selector:
    matchLabels:
      app: dbgate
  replicas: 1
  template:
    metadata:
      labels:
        app: dbgate
    spec:
      containers:
        #docker run -d --hostname my-rabbit --name some-rabbit-1 rabbitmq:3 -p 5672:5672 -p 15672:15672
        - image: dbgate/dbgate
          name: dbgate
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"